# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'    
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'curl -k -u $ZEROBUGUID:$ZEROBUGTOKEN --request POST -H "Content-Type:application/json" -d ''{"pit":"130","targetid":"VUuNrXyj1ppIKcOu2HXq1597850126","ci":"GitLab","tipo":"8"}'' https://zerobug.co/ScanTarget/'
